zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.9.0
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuateio-local-kafka:0.9.0
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  image: eventuateio/eventuateio-local-mysql:0.9.0
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw


cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.9.0
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb

apigateway:
  extends:
    file: docker-compose-common.yml
    service: apigateway
  links:
    - accountsservice
    - transactionsservice
    - accountsviewservice
    - customersservice
    - customersviewservice
    - mongodb

accountsservice:
  extends:
    file: docker-compose-common.yml
    service: accountsservice
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword


transactionsservice:
  extends:
    file: docker-compose-common.yml
    service: transactionsservice
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

accountsviewservice:
  extends:
    file: docker-compose-common.yml
    service: accountsviewservice
  links:
    - mongodb
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword


customersservice:
  extends:
    file: docker-compose-common.yml
    service: customersservice
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

customersviewservice:
  extends:
    file: docker-compose-common.yml
    service: customersviewservice
  links:
    - mongodb
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/mydb
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
